# Generated by Django 4.1.6 on 2023-03-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300)),
                ('follower', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
